# Generated by Django 4.2.4 on 2023-09-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('image', models.ImageField(upload_to='about', verbose_name='Imagen')),
                ('descript', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('urlFacebook', models.URLField(blank=True, null=True, verbose_name='Enlace Facebook')),
                ('urlInstagram', models.URLField(blank=True, null=True, verbose_name='Enlace Instagram')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modificación')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servivcios',
                'ordering': ['created'],
            },
        ),
    ]
