# Generated by Django 4.2.4 on 2023-09-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['created'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Equipo de trabajo'},
        ),
    ]
